name: build-linux-wheels
on: workflow_dispatch           # 手动触发

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux wheels (Py3.10)
        run: |
          python -m pip install --upgrade pip
          pip download -d wheels \
            --only-binary=:all: \
            --platform manylinux2014_x86_64 \
            --implementation cp --python-version 310 --abi cp310 \
            -r requirements.txt
          tar -czf wheels-linux310.tar.gz wheels

      - uses: actions/upload-artifact@v3
        with:
          name: linux-wheels
          path: wheels-linux310.tar.gz
