name: linux38-wheels
on: workflow_dispatch

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect wheels inside python:3.8 container
        run: |
          docker run --rm -v "$PWD:/work" -w /work \
            python:3.8-slim bash -c "
              pip install -U pip &&
              pip download -d wheels --only-binary=:all: -r requirements.txt"
          tar -czf wheels-linux38.tar.gz wheels

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels38
          path: wheels-linux38.tar.gz
