name: linux310-wheels
on: workflow_dispatch          # 手动触发

jobs:
  wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) 用官方 python:3.10 容器编译所有 wheel
      - name: Build wheels inside python:3.10
        run: |
          docker run --rm \
            -v "$PWD:/work" -w /work \
            python:3.10 \
            bash -c "apt-get update -qq && apt-get install -y build-essential curl && \
                     python -m pip install -U pip wheel setuptools && \
                     pip wheel -w wheels -r requirements.txt"

      # 2) 打包
      - name: Tar wheels
        run: tar -czf wheels-linux310.tar.gz wheels

      # 3) 上传
      - uses: actions/upload-artifact@v3
        with:
          name: linux-wheels
          path: wheels-linux310.tar.gz
